server:
  port: 9104

spring:
  cloud:
    gcp:
      project-id: valid-might-365117
      credentials:
        location: classpath:valid-might-365117-ad47552a59d8.json

#  spring.cloud.gcp.project-id=valid-might-365117
#  spring.cloud.gcp.credentials.location=classpath:valid-might-365117-ad47552a59d8.json


#logging.file.name =log/AppLogs.log
#logging.level= DEBUG
#
#logging.level.org.springframework.web= INFO
#logging.level.org.springframework= INFO
#log4j.logger.org.springframework= INFO
#logging.level.org.hibernate.type=trace
#logging.level.org.hibernate=INFO
#logging.level.org.hibernate.SQL=DEBUG
#loging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE